name: Test
on:
  pull_request:
  push:
    branches:
      - master
      - github-actions-test-*
jobs:
  test:
    strategy:
      matrix:
        node: ['18.x']
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g yarn@1.22.19
      - run: yarn
      - run: yarn build
      - run: yarn test:ci
